apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-nodejs-app-deployment
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeserver
        image: username/image-name:latest
        ports:
        - containerPort: 3000